### PR TITLE
✨  feat(dropdown): some little updates

### PR DESCRIPTION
**Pull request by hirsch88**

### CODE REVIEW

**Comment by incubator-tekton** [comment]
:rocket: Welcome to Baloise ChatOps based GitOps Bot :tada:
                                
    - If you want to enable preview environments for this PullRequest, comment with `/preview`. 
    - If you want to disable the preview environment for this PR, comment with `/undeploy`. 
    - If you need help or want to see the docs, comment with `/help`. 
                                
    Make sure to refresh this page after submitting a command.
    Preview environments can be redeployed automatically if you enable the webhook for updates to the source branch. :new:
    
    Have fun building awesome apps! :hammer:  :whale2:  :truck:  :ship:

**Comment by hirsch88** [comment]
**🚀 Snapshot Version Released!**

Version: `16.2.1-snapshot.1436-61ea3efea`

[Check out the release on GitHub ↗︎](https://github.com/baloise/design-system/actions/runs/10522833976)

**Review by yannickholzenkamp — APPROVED** [review]

**Comment by hirsch88** [comment]
**🚀 Snapshot Version Released!**

Version: `16.2.1-snapshot.1436-16ca427e6`

[Check out the release on GitHub ↗︎](https://github.com/baloise/design-system/actions/runs/10523236933)

**Comment by hirsch88** [comment]
**🚀 Snapshot Version Released!**

Version: `16.2.1-snapshot.1436-79713df70`

[Check out the release on GitHub ↗︎](https://github.com/baloise/design-system/actions/runs/10524173570)

**Comment by hirsch88** [comment]
**📸 Create Base Image finished!**

Specs: `bal-dropdown.visual.cy.ts`

[Check out the action on GitHub ↗︎](https://github.com/baloise/design-system/actions/runs/10526274447)

**Pull request merged**
