### PR TITLE
🐛 fix(testing): npm package exports

### PR DESCRIPTION
**Pull request by hirsch88**

### CODE REVIEW

**Review by hirsch88 — COMMENTED** [review]
/snapshot

**Comment by incubator-tekton** [comment]
:rocket: Welcome to Baloise ChatOps based GitOps Bot :tada:
                                
    - If you want to enable preview environments for this PullRequest, comment with `/preview`. 
    - If you want to disable the preview environment for this PR, comment with `/undeploy`. 
    - If you need help or want to see the docs, comment with `/help`. 
                                
    Make sure to refresh this page after submitting a command.
    Preview environments can be redeployed automatically if you enable the webhook for updates to the source branch. :new:
    
    Have fun building awesome apps! :hammer:  :whale2:  :truck:  :ship:

**Comment by hirsch88** [comment]
**🚀 Snapshot Version Released!**

Version: `16.0.0-snapshot.1346-6d38d8b0d`

[Check out the release on GitHub ↗︎](https://github.com/baloise/design-system/actions/runs/8246480592)

**Comment by hirsch88** [comment]
**🚀 Snapshot Version Released!**

Version: `16.0.0-snapshot.1346-27e6d77e0`

[Check out the release on GitHub ↗︎](https://github.com/baloise/design-system/actions/runs/8246648505)

**Pull request merged**
