### PR TITLE
feat(icon) Convert SVG background icons to web font

### PR DESCRIPTION
**Pull request by RudyBricks**

### CODE REVIEW

**Comment by christiansiegel** [comment]
The icon readme contains the following sentence. Is this still the case?

> The Baloise SVG icons have been converted with this [tool](https://websemantics.uk/tools/svg-to-background-image-conversion/).

**Review by hirsch88 — APPROVED** [review]
Very nice thank you

**Comment by RudyBricks** [comment]
> The icon readme contains the following sentence. Is this still the case?
> 
> > The Baloise SVG icons have been converted with this [tool](https://websemantics.uk/tools/svg-to-background-image-conversion/).

Your right, I updated the readme as well

**Pull request merged**
