### PR TITLE
🐛 fix(devkit): adjust tsconfig for build

### PR DESCRIPTION
**Pull request by hirsch88**

### CODE REVIEW

**Comment by incubator-tekton** [comment]
:rocket: Welcome to Baloise ChatOps based GitOps Bot :tada:
                                
    - If you want to enable preview environments for this PullRequest, comment with `/preview`. 
    - If you want to disable the preview environment for this PR, comment with `/undeploy`. 
    - If you need help or want to see the docs, comment with `/help`. 
                                
    Make sure to refresh this page after submitting a command.
    Preview environments can be redeployed automatically if you enable the webhook for updates to the source branch. :new:
    
    Have fun building awesome apps! :hammer:  :whale2:  :truck:  :ship:

**Comment by hirsch88** [comment]
**🚀 Snapshot Version Released!**

Version: `16.0.1-snapshot.1361-ba0e384ff`

[Check out the release on GitHub ↗︎](https://github.com/baloise/design-system/actions/runs/8340577810)

**Comment by hirsch88** [comment]
**🚀 Snapshot Version Released!**

Version: `16.0.1-snapshot.1361-696e89e41`

[Check out the release on GitHub ↗︎](https://github.com/baloise/design-system/actions/runs/8341048017)

**Comment by hirsch88** [comment]
**🚀 Snapshot Version Released!**

Version: `16.0.1-snapshot.1361-1837509de`

[Check out the release on GitHub ↗︎](https://github.com/baloise/design-system/actions/runs/8342901134)

**Pull request merged**
